= player-ranking

A Kotlin/Ktor project containing:

* a REST API for tournament players ranking management
* an Angular webapp for those players visualization

It is implemented using:

* https://kotlinlang.org/[Kotlin]
* https://ktor.io/[Ktor]
* https://insert-koin.io/[Koin DI framework]
* https://www.mongodb.com/[MongoDB]
* https://angular.io/[Angular]

== Getting started

The easiest and fastest way to run the application is <<_using_docker_compose, using Docker Compose>>. +
Otherwise, if you don't want to rely on Docker, you'll have to <<_building_manually, build>> its parts manually.

[#_using_docker_compose]
=== Using Docker Compose
The provided `run.sh` bash file uses https://docs.docker.com/compose/[Docker Compose] for building both the server and the client webapp. +
It even sets up the database for you!

MacOS and Windows users should install https://docs.docker.com/desktop/[Docker Desktop] which includes Compose along with other Docker tools.

Linux's users will have to install those two items separately :

* https://docs.docker.com/engine/install/[Docker Engine]
* https://docs.docker.com/compose/install/[Docker Compose]

Once Docker is available, starting the application is quite simple using the provided bash script:
....
./run.sh up
....

The webapp should be available at http://localhost:8080

Stopping the application (and docker infrastructure) is just as simple:
....
./run.sh down
....

[#_building_manually]
=== Building manually

==== Build the server
As a prerequisite, you'll need a valid https://openjdk.java.net/[JDK] installation on your machine.

You'll also need a running https://www.mongodb.com/[MongoDB] instance, preferably on _localhost:27017_. +
Change the server configuration accordingly otherwise (see `src/main/resources/application.conf`) or define a _MONGODB_URI_ environment variable.

Navigate to the location where you cloned the project:
....
cd <path>/<to>/<player-ranking>/server
....

Using gradlew, build the server:
....
gradlew clean build
....

Start it with:
....
gradlew run
....

==== Building the client (using AngularCli)
As a prerequisite, you'll need a valid https://nodejs.org/en/about/releases/[Node.js] installation on your machine.

Once Node.js and NPM are available, install AngularCli:
....
npm install -g @angular/cli
....

Navigate to the location where you cloned the project:
....
cd <path>/<to>/<player-ranking>/client
....

Locally serve the project (useful in development phase) using:
....
ng serve
....

You can also build it for a production release using:
....
ng build --configuration="production"
....


== API documentation
[source, http request]
----
include::server/src/test/resources/endpoint-tests.http[]
----

== Misc
A strange error appears randomly in the console (the app doesn't crash):

....
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:367)
at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:398)
at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.ktor.server.netty.EventLoopGroupProxy$Companion$create$factory$1$1.run(NettyApplicationEngine.kt:241)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:832)
....

Looks like it is  a known issue: https://youtrack.jetbrains.com/issue/KTOR-646.