###
POST http://localhost:8080/players
Content-Type: application/json

{
  "pseudo": "bill",
  "points": 1
}

###
POST http://localhost:8080/players
Content-Type: application/json

{
  "pseudo": "bob",
  "points": 5
}

###
POST http://localhost:8080/players
Content-Type: application/json

{
  "pseudo": "john",
  "points": 10
}

###
GET http://localhost:8080/players

###
GET http://localhost:8080/players/bill
Accept: application/json