### Create player 'bill'
POST http://localhost:8080/api/v1/players
Content-Type: application/json

{
  "pseudo": "bill",
  "points": 1
}

### Create player 'bob'
POST http://localhost:8080/api/v1/players
Content-Type: application/json

{
  "pseudo": "bob",
  "points": 5
}

### Create player 'john'
POST http://localhost:8080/api/v1/players
Content-Type: application/json

{
  "pseudo": "john",
  "points": 10
}

### Update john's points
PUT http://localhost:8080/api/v1/players/john/points
Content-Type: application/json

{
  "points": 100
}

### List all players (sorted by rank)
GET http://localhost:8080/api/v1/players

### Get player 'bill'
GET http://localhost:8080/api/v1/players/bill
Accept: application/json

### Delete all players
DELETE http://localhost:8080/api/v1/players